server:
  port: 9099
spring:
  datasource:
    url: ENC(ip5pQuH0CoxuB3WCVp9PDNtYqtZfiUuaMZKtAA+LP9sKH4JlyRAANVrAitzoNDfP+OTz/2BsYWbkTEm8p900JZO2ABTgHASJDgPJSoBCAeOLHOgRcpoxKg==)
    driver-class-name : oracle.jdbc.OracleDriver
    username: ENC(0J2OycehFY3bZaofp1ikEw==)
    password: ENC(vL2XAsX7VVd6zPvsPJhPFmqYOzAE5jW6)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password :


