server:
  port: 9099
spring:
  #  datasource:
#    url: ENC(wi6yFg2Zwe0qzft9vToYXQOEEcg4UuZX6v/hlJEF1fWNmVB+0AvhL7cXUc27urBvw4+L2mrKWRw/na4d1Bwa/4OQqCGzFhcuR8VTZZQ0LqePVxhJiGXlxA==)
#    driver-class-name : oracle.jdbc.OracleDriver
#    username: ENC(0J2OycehFY3bZaofp1ikEw==)
#    password: ENC(vL2XAsX7VVd6zPvsPJhPFmqYOzAE5jW6)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: YWFhaWN1LWdldHRvLXNwcmluZy1ib290LWp3dC1zZWNyZXQK

  access-token-expiration-seconds: 300
  # 86400*7*2 ( 2주 )
  refresh-token-expiration-seconds: 1209600

oauth:
  host-url: http://localhost:3000
  kakao:
    rest-api-key: ENC(KfzC1BmdAWFg5cgx7pB15RP4goeXOCT819KOgI2GaDMwIktsqW99K+vAQcFZP1gd)
    url: /callback/kakao

front:
  host-url: http://localhost:3000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password :

logging:
  level:
    com.yummythings.getto: DEBUG
