server:
  port: 9099
spring:
  datasource:
    url: ENC(cvKKa+NtpVk+jPmcN4vA1y5HUlvIR6kYS9MdGma8tOzdypu2RJpO4eofi/svEQHMq72qKHVvGF/b4qTJa2qqKkH2CKuD6W9x)
    driver-class-name : oracle.jdbc.OracleDriver
    username: ENC(0J2OycehFY3bZaofp1ikEw==)
    password: ENC(vL2XAsX7VVd6zPvsPJhPFmqYOzAE5jW6)
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: "e82fa866da628313f8a8e42774b72077"
#            redirect-uri: "{baseUrl}/{action}/oauth?code={registrationId}"
#            #http://localhost:9099/oauth?code=test
#            # http://localhost:8080/login/oauth2/code/kakao
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
oauth:
  host-url: https://api.yummy-things.xyz
  kakao:
    rest-api-key: ENC(KfzC1BmdAWFg5cgx7pB15RP4goeXOCT819KOgI2GaDMwIktsqW99K+vAQcFZP1gd)
    url: /oauth/kakao

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password :

logging:
  level:
    root: INFO
  file:
    name: "/var/logs/getto-api.log"
    path: "/var/logs"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_PATH}/history/getto-api.%d{yyyy-MM-dd}_%i.zip"
      max-history: 7
      max-file-size: 100MB
      total-size-cap: 2GB
