server:
  port: 9099
spring:
  datasource:
    url: ENC(cvKKa+NtpVk+jPmcN4vA1y5HUlvIR6kYS9MdGma8tOzdypu2RJpO4eofi/svEQHMq72qKHVvGF/b4qTJa2qqKkH2CKuD6W9x)
    driver-class-name : oracle.jdbc.OracleDriver
    username: ENC(0J2OycehFY3bZaofp1ikEw==)
    password: ENC(vL2XAsX7VVd6zPvsPJhPFmqYOzAE5jW6)

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: YWFhaWN1LWdldHRvLXNwcmluZy1ib290LWp3dC1zZWNyZXQK

  access-token-expiration-seconds: 300
  # 86400*7*2 ( 2주 )
  refresh-token-expiration-seconds: 1209600

oauth:
  host-url: https://www.yummy-things.xyz
  kakao:
    rest-api-key: ENC(KfzC1BmdAWFg5cgx7pB15RP4goeXOCT819KOgI2GaDMwIktsqW99K+vAQcFZP1gd)
    url: /callback/kakao

front:
  host-url: https://www.yummy-things.xyz

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password :

logging:
  level:
    root: INFO
  file:
    name: "/var/logs/getto-api.log"
    path: "/var/logs"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_PATH}/history/getto-api.%d{yyyy-MM-dd}_%i.zip"
      max-history: 7
      max-file-size: 100MB
      total-size-cap: 2GB